#!/usr/bin/env python3
with open('src/evaluation/__init__.py', 'w', encoding='utf-8') as f:
    f.write('from .evaluator import OfflineEvaluator\n')
    f.write('from .metrics_engine import MetricsEngine\n')
    f.write('from .benchmark_dataset import BenchmarkDataset, MedicalBenchmarkLoader\n')
    f.write('from .llm_judge import LLMJudge, JudgeResult\n')
    f.write('from .threshold_checker import ThresholdChecker, ThresholdConfig, CheckResult\n')
    f.write('\n')
    f.write('__all__ = [\n')
    f.write('    "OfflineEvaluator",\n')
    f.write('    "MetricsEngine",\n')
    f.write('    "BenchmarkDataset",\n')
    f.write('    "MedicalBenchmarkLoader",\n')
    f.write('    "LLMJudge",\n')
    f.write('    "JudgeResult",\n')
    f.write('    "ThresholdChecker",\n')
    f.write('    "ThresholdConfig",\n')
    f.write('    "CheckResult",\n')
    f.write(']\n')
print('File written successfully')