import re
from typing import List, Dict, Any, Optional, Tuple
from collections import defaultdict
from loguru import logger

from ..core.medical_schema import MedicalEntityType


class EntityDisambiguator:
    """实体消歧模块 - 识别并合并指称同一实体的不同表述"""

    def __init__(self):
        self.synonym_rules = self._load_synonym_rules()
        self.abbreviation_map = self._load_abbreviation_map()
        self.icd10_mapping = self._load_icd10_mapping()
        self.umls_mapping = self._load_umls_mapping()
        
        self._terminology_service = None
        try:
            from ..terminology.service import TerminologyService
            self._terminology_service = TerminologyService()
            logger.info("TerminologyService loaded successfully")
        except Exception as e:
            logger.warning(f"Failed to load terminology service: {e}")
            self._terminology_service = None

    def _load_synonym_rules(self) -> Dict[str, Dict[str, List[str]]]:
        """加载医疗实体同义词规则 - 基于ICD-10和UMLS标准"""
        return {
            "Disease": {
                "高血压": ["高血压病", "原发性高血压", "继发性高血压", "HTN", "high blood pressure", "血压高"],
                "糖尿病": ["糖尿病 mellitus", "DM", "高血糖", "血糖高", "diabetes", "II型糖尿病", "2型糖尿病", "1型糖尿病", "I型糖尿病"],
                "肺炎": ["肺部感染", "pneumonia", "细菌性肺炎", "病毒性肺炎"],
                "冠心病": ["冠状动脉粥样硬化性心脏病", "coronary heart disease", "CHD"],
                "哮喘": ["支气管哮喘", "asthma", "过敏性哮喘"],
                "脑梗死": ["脑卒中", "中风", "cerebral infarction", "CVA"],
                "心肌梗死": ["心梗", "myocardial infarction", "MI"],
                "胃炎": ["慢性胃炎", "胃黏膜炎症", "急性胃炎"],
                "关节炎": ["关节炎症", "类风湿关节炎", "rheumatoid arthritis", "RA"],
                "肝炎": ["肝脏炎症", "病毒性肝炎", "hepatitis", "甲肝", "乙肝", "丙肝"],
                "肾炎": ["肾小球肾炎", "renal inflammation"],
                "支气管炎": ["bronchitis", "急性支气管炎", "慢性支气管炎", "COPD"],
                "肺结核": ["肺痨", "tuberculosis", "TB"],
                "艾滋病": ["获得性免疫缺陷综合征", "AIDS", "HIV感染"],
                "癌症": ["恶性肿瘤", "cancer", "carcinoma"],
                "白血病": ["血癌", "leukemia"],
                "淋巴瘤": ["lymphoma"],
                "胃癌": ["stomach cancer", "gastric cancer"],
                "肺癌": ["lung cancer", "pulmonary carcinoma"],
                "肝癌": ["liver cancer", "hepatic carcinoma"],
                "乳腺癌": ["breast cancer"],
                "结肠癌": ["colon cancer", "colorectal cancer"],
                "直肠癌": ["rectal cancer"],
                "胰腺癌": ["pancreatic cancer"],
                "卵巢癌": ["ovarian cancer"],
                "前列腺癌": ["prostate cancer"],
                "甲状腺癌": ["thyroid cancer"],
                "胆结石": ["胆石症", "gallstones"],
                "肾结石": ["肾石症", "kidney stones", "renal calculi"],
                "胆囊炎": ["cholecystitis"],
                "阑尾炎": ["appendicitis"],
                "胰腺炎": ["pancreatitis"],
                "肠炎": ["enteritis", "bowel inflammation"],
                "肠梗阻": ["intestinal obstruction"],
                "贫血": ["anemia", "血虚"],
                "血小板减少": ["thrombocytopenia"],
                "系统性红斑狼疮": ["SLE", "lupus"],
                "强直性脊柱炎": ["ankylosing spondylitis", "AS"],
                "痛风": ["gout", "高尿酸血症"],
                "骨质疏松": ["osteoporosis"],
                "骨折": ["bone fracture", "fracture"],
                "脱位": ["dislocation"],
                "扭伤": ["sprain"],
                "烧伤": ["burn"],
                "冻伤": ["frostbite"],
                "中毒": ["poisoning", "intoxication"],
                "过敏": ["allergy", "hypersensitivity"],
                "休克": ["shock"],
                "昏迷": ["coma"],
                "癫痫": ["epilepsy", "羊癫疯", "seizure"],
                "帕金森病": ["Parkinson's disease", "震颤麻痹", "PD"],
                "阿尔茨海默病": ["Alzheimer's disease", "老年痴呆", "dementia", "AD"],
                "多发性硬化": ["multiple sclerosis", "MS"],
                "抑郁症": ["depression", "忧郁症"],
                "焦虑症": ["anxiety", "焦虑障碍"],
                "精神分裂症": ["schizophrenia"],
                "失眠": ["insomnia", "睡眠障碍"],
                "肥胖症": ["obesity", "肥胖"],
                "甲状腺功能亢进": ["甲亢", "hyperthyroidism", "Graves' disease"],
                "甲状腺功能减退": ["甲减", "hypothyroidism"],
                "骨关节炎": ["osteoarthritis", "OA"],
                "偏头痛": ["migraine"],
                "带状疱疹": ["herpes zoster", "shingles"],
                "流感": ["influenza", "流行性感冒"],
                "普通感冒": ["common cold", "感冒"],
                "手足口病": ["hand foot and mouth disease", "HFMD"],
                "水痘": ["chickenpox", "varicella"],
                "麻疹": ["measles"],
                "风疹": ["rubella", "德国麻疹"],
                "流行性腮腺炎": ["mumps", "痄腮"],
                "猩红热": ["scarlet fever"],
                "百日咳": ["pertussis", "whooping cough"],
                "白喉": ["diphtheria"],
                "破伤风": ["tetanus"],
                "狂犬病": ["rabies", "恐水症"],
                "病毒性肝炎": ["viral hepatitis"],
                "梅毒": ["syphilis"],
                "淋病": ["gonorrhea"],
                "尖锐湿疣": ["condyloma acuminatum", "HPV感染"],
                "细菌性痢疾": ["bacillary dysentery", "菌痢"],
                "伤寒": ["typhoid fever"],
                "霍乱": ["cholera"],
                "疟疾": ["malaria"],
                "登革热": ["dengue fever"],
                "SARS": ["严重急性呼吸综合征", "非典型肺炎"],
                "COVID-19": ["新冠肺炎", "新型冠状病毒肺炎", "新冠"],
                "高血压危象": ["hypertensive crisis"],
                "心律失常": ["arrhythmia", "心律不齐"],
                "房颤": ["atrial fibrillation", "心房颤动"],
                "心力衰竭": ["heart failure", "心衰"],
                "心绞痛": ["angina", "angina pectoris"],
                "心肌炎": ["myocarditis"],
                "心包炎": ["pericarditis"],
                "心脏瓣膜病": ["valvular heart disease"],
                "先天性心脏病": ["congenital heart disease", "先心病"],
                "胸腔积液": ["pleural effusion"],
                "气胸": ["pneumothorax"],
                "肺栓塞": ["pulmonary embolism", "PE"],
                "慢性阻塞性肺疾病": ["chronic obstructive pulmonary disease", "COPD"],
                "支气管扩张": ["bronchiectasis"],
                "肺脓肿": ["lung abscess"],
                "间质性肺病": ["interstitial lung disease"],
                "呼吸衰竭": ["respiratory failure"],
                "睡眠呼吸暂停": ["sleep apnea", "OSA"],
                "鼻窦炎": ["sinusitis"],
                "扁桃体炎": ["tonsillitis"],
                "咽炎": ["pharyngitis"],
                "喉炎": ["laryngitis"],
                "中耳炎": ["otitis media"],
                "青光眼": ["glaucoma"],
                "白内障": ["cataract"],
                "视网膜病变": ["retinopathy"],
                "黄斑病变": ["macular degeneration"],
                "牙周病": ["periodontal disease", "牙周炎"],
                "龋齿": ["dental caries", "蛀牙"],
                "牙髓炎": ["pulpitis"],
                "口腔溃疡": ["oral ulcer", "口疮"],
                "脂溢性皮炎": ["seborrheic dermatitis"],
                "湿疹": ["eczema"],
                "银屑病": ["psoriasis", "牛皮癣"],
                "荨麻疹": ["urticaria", "风疹块"],
                "痤疮": ["acne", "青春痘"],
                "脱发": ["alopecia", "斑秃"],
                "白癜风": ["vitiligo", "白斑病"],
                "黄褐斑": ["melasma"],
                "过敏性紫癜": ["Henoch-Schönlein purpura"],
                "深静脉血栓": ["deep vein thrombosis", "DVT"],
                "短暂性脑缺血发作": ["transient ischemic attack", "TIA", "小中风"],
                "脑出血": ["cerebral hemorrhage"],
                "蛛网膜下腔出血": ["subarachnoid hemorrhage", "SAH"],
                "多发性硬化": ["multiple sclerosis", "MS"],
                "肌萎缩侧索硬化": ["amyotrophic lateral sclerosis", "ALS", "渐冻症"],
                "重症肌无力": ["myasthenia gravis", "MG"],
                "吉兰-巴雷综合征": ["Guillain-Barré syndrome", "GBS"],
                "腕管综合征": ["carpal tunnel syndrome"],
                "三叉神经痛": ["trigeminal neuralgia"],
                "面神经麻痹": ["facial nerve palsy", "Bell麻痹"],
                "丛集性头痛": ["cluster headache"],
                "紧张性头痛": ["tension-type headache"],
                "双相情感障碍": ["bipolar disorder", "躁郁症"],
                "创伤后应激障碍": ["post-traumatic stress disorder", "PTSD"],
                "强迫症": ["obsessive-compulsive disorder", "OCD"],
                "注意缺陷多动障碍": ["attention deficit hyperactivity disorder", "ADHD"],
                "自闭症谱系障碍": ["autism spectrum disorder", "ASD"],
                "抽动秽语综合征": ["Tourette syndrome"],
                "神经性厌食": ["anorexia nervosa"],
                "神经性贪食": ["bulimia nervosa"],
                "酒精使用障碍": ["alcohol use disorder"],
                "药物使用障碍": ["drug use disorder"],
                "创伤性脑损伤": ["traumatic brain injury", "TBI"],
                "脊髓损伤": ["spinal cord injury", "SCI"],
                "败血症": ["sepsis"],
                "多器官功能障碍综合征": ["multiple organ dysfunction syndrome", "MODS"],
                "尿路感染": ["urinary tract infection", "UTI"],
                "脑膜炎": ["meningitis"],
                "脑炎": ["encephalitis"],
                "骨髓炎": ["osteomyelitis"],
                "化脓性关节炎": ["septic arthritis"],
                "炎性肠病": ["inflammatory bowel disease"],
                "克罗恩病": ["Crohn's disease"],
                "溃疡性结肠炎": ["ulcerative colitis"],
                "肠易激综合征": ["irritable bowel syndrome", "IBS"],
                "胃食管反流病": ["gastroesophageal reflux disease", "GERD"],
                "消化性溃疡": ["peptic ulcer"],
                "肝硬化": ["liver cirrhosis"],
                "脂肪肝": ["fatty liver"],
                "肝脓肿": ["liver abscess"],
                "胆道梗阻": ["biliary obstruction"],
                "急性胰腺炎": ["acute pancreatitis"],
                "慢性胰腺炎": ["chronic pancreatitis"],
                "急性肾损伤": ["acute kidney injury", "AKI"],
                "慢性肾脏病": ["chronic kidney disease", "CKD"],
                "肾病综合征": ["nephrotic syndrome"],
                "肾衰竭": ["renal failure"],
                "尿毒症": ["uremia"],
                "膀胱炎": ["cystitis"],
                "尿道炎": ["urethritis"],
                "前列腺炎": ["prostatitis"],
                "盆腔炎": ["pelvic inflammatory disease", "PID"],
                "子宫内膜异位症": ["endometriosis"],
                "多囊卵巢综合征": ["polycystic ovary syndrome", "PCOS"],
                "子宫肌瘤": ["uterine fibroid"],
                "卵巢囊肿": ["ovarian cyst"],
                "乳腺增生": ["breast hyperplasia"],
                "乳腺炎": ["mastitis"],
                "甲状腺结节": ["thyroid nodule"],
                "甲状腺炎": ["thyroiditis"],
                "痛风性关节炎": ["gouty arthritis"],
                "假性痛风": ["pseudogout"],
                "反应性关节炎": ["reactive arthritis"],
                "银屑病关节炎": ["psoriatic arthritis"],
                "干燥综合征": ["Sjögren's syndrome"],
                "硬皮病": ["systemic sclerosis"],
                "多发性肌炎": ["polymyositis"],
                "皮肌炎": ["dermatomyositis"],
                "结节病": ["sarcoidosis"],
                "大动脉炎": ["Takayasu arteritis"],
                "巨细胞动脉炎": ["giant cell arteritis"],
                "风湿性多肌痛": ["polymyalgia rheumatica"],
                "骨质疏松症": ["osteoporosis"],
                "骨质增生": ["osteophyte", "骨刺"],
                "椎间盘突出": ["herniated disc"],
                "椎管狭窄": ["spinal stenosis"],
                "脊柱侧弯": ["scoliosis"],
                "颈椎病": ["cervical spondylosis"],
                "腰椎病": ["lumbar spondylosis"],
                "滑膜炎": ["synovitis"],
                "肌腱炎": ["tendinitis"],
                "腱鞘炎": ["tenosynovitis"],
                "滑囊炎": ["bursitis"],
                "纤维肌痛": ["fibromyalgia"],
                "慢性疲劳综合征": ["chronic fatigue syndrome"],
            },
            "Symptom": {
                "咳嗽": ["干咳", "湿咳", "cough", "咳痰", "呛咳"],
                "发热": ["发烧", "体温升高", "fever", "发烧", "高热", "低热"],
                "头痛": ["头疼", "headache", "偏头痛", "migraine", "脑袋疼"],
                "胸痛": ["胸闷", "chest pain", "胸口痛", "心前区疼痛"],
                "乏力": ["疲倦", "疲劳", "fatigue", "无力"],
                "恶心": ["想吐", "nausea"],
                "呕吐": ["呕", "vomiting", "干呕", "呕血"],
                "腹泻": ["拉肚子", "diarrhea", "泄泻", "水样便"],
                "便秘": ["constipation", "大便干结"],
                "腹痛": ["abdominal pain", "肚子痛", "胃疼"],
                "腹胀": ["bloating", "腹部胀气"],
                "食欲不振": ["anorexia", "没胃口", "不想吃饭"],
                "体重下降": ["weight loss", "消瘦", "体重减轻"],
                "呼吸困难": ["气短", "喘不上气", "dyspnea", "喘息"],
                "头晕": ["眩晕", "dizziness", "头昏"],
                "眩晕": ["vertigo", "头晕目眩"],
                "心悸": ["palpitation", "心慌", "心跳加速"],
                "失眠": ["insomnia", "睡不着", "睡眠障碍"],
                "嗜睡": ["drowsiness", "总想睡觉"],
                "意识模糊": ["confusion", "神志不清"],
                "记忆力减退": ["memory loss", "健忘"],
                "注意力不集中": ["poor concentration"],
                "情绪低落": ["depressed mood", "心情郁闷"],
                "烦躁不安": ["irritability", "心烦"],
                "焦虑": ["anxiety", "紧张不安"],
                "抑郁": ["depression", "情绪低落"],
                "关节痛": ["joint pain", "关节酸痛"],
                "肌肉痛": ["muscle pain", "muscle ache", "酸痛"],
                "背痛": ["back pain", "腰疼", "腰酸"],
                "颈痛": ["neck pain", "脖子疼"],
                "肩痛": ["shoulder pain"],
                "腿痛": ["leg pain"],
                "手臂痛": ["arm pain"],
                "麻木": ["numbness", "发麻"],
                "刺痛": ["tingling", "针刺痛"],
                "肿胀": ["swelling", "浮肿", "水肿"],
                "发红": ["redness", "红肿"],
                "瘙痒": ["itching", "痒"],
                "皮疹": ["rash", "皮肤疹", "斑丘疹"],
                "出血": ["bleeding", "流血"],
                "瘀斑": ["bruise", "淤青", "瘀青"],
                "黄疸": ["jaundice", "皮肤发黄", "巩膜黄染"],
                "口干": ["dry mouth", "口渴"],
                "口苦": ["bitter taste", "嘴里发苦"],
                "口臭": ["bad breath", "口气"],
                "牙龈出血": ["gingival bleeding"],
                "鼻出血": ["nosebleed", "流鼻血", "epistaxis"],
                "耳痛": ["ear pain", "耳朵疼"],
                "耳鸣": ["tinnitus", "耳朵响"],
                "听力下降": ["hearing loss", "听不清楚"],
                "视力模糊": ["blurred vision", "看不清"],
                "视力下降": ["vision loss"],
                "眼痛": ["eye pain", "眼睛疼"],
                "流泪": ["tearing", "流眼泪"],
                "鼻塞": ["nasal congestion", "鼻子堵"],
                "流涕": ["runny nose", "流鼻涕"],
                "打喷嚏": ["sneezing", "喷嚏"],
                "咽喉痛": ["sore throat", "嗓子疼", "喉咙痛"],
                "声音嘶哑": ["hoarseness", "声音哑"],
                "吞咽困难": ["dysphagia", "吃东西费劲"],
                "排尿困难": ["dysuria", "小便费劲"],
                "尿频": ["frequency", "老想上厕所"],
                "尿急": ["urgency", "憋不住"],
                "尿痛": ["painful urination", "小便疼"],
                "血尿": ["hematuria", "尿里有血"],
                "蛋白尿": ["proteinuria", "尿蛋白"],
                "尿量减少": ["oliguria", "尿少"],
                "尿失禁": ["incontinence", "尿裤子"],
                "月经不调": ["menstrual irregularity", "例假不准"],
                "痛经": ["dysmenorrhea", "来月经肚子疼"],
                "阴道出血": ["vaginal bleeding"],
                "白带异常": ["abnormal vaginal discharge"],
                "阳痿": ["impotence", "勃起功能障碍", "ED"],
                "早泄": ["premature ejaculation"],
                "关节肿胀": ["joint swelling"],
                "关节僵硬": ["joint stiffness"],
                "肌肉萎缩": ["muscle atrophy"],
                "肌肉无力": ["muscle weakness"],
                "步态异常": ["gait abnormality"],
                "肢体麻木": ["limb numbness"],
                "感觉异常": ["paresthesia"],
                "抽搐": ["convulsion"],
                "震颤": ["tremor", "手抖"],
                "共济失调": ["ataxia"],
                "言语不清": ["dysarthria"],
                "失语": ["aphasia"],
                "视野缺损": ["visual field defect"],
                "复视": ["diplopia"],
                "眼震": ["nystagmus"],
                "瞳孔异常": ["pupillary abnormality"],
                "眼睑下垂": ["ptosis"],
                "眼球突出": ["exophthalmos"],
                "眼压升高": ["increased intraocular pressure"],
                "结膜充血": ["conjunctival injection"],
                "牙周炎": ["periodontitis"],
                "牙龈炎": ["gingivitis"],
                "口角炎": ["angular cheilitis"],
                "皮肤发红": ["skin redness"],
                "皮肤发热": ["skin warmth"],
                "皮肤干燥": ["skin dryness"],
                "皮肤脱屑": ["skin scaling"],
                "皮肤水疱": ["skin blister"],
                "皮肤糜烂": ["skin erosion"],
                "皮肤溃疡": ["skin ulcer"],
                "皮肤瘢痕": ["skin scar"],
                "皮肤色素沉着": ["skin pigmentation"],
                "皮肤萎缩": ["skin atrophy"],
                "皮肤增厚": ["skin thickening"],
                "皮肤角化": ["skin keratinization"],
                "皮下结节": ["subcutaneous nodule"],
                "淋巴结肿大": ["lymphadenopathy"],
                "肝肿大": ["hepatomegaly"],
                "脾肿大": ["splenomegaly"],
                "肾肿大": ["nephromegaly"],
                "心脏扩大": ["cardiomegaly"],
                "胸腔积液": ["pleural effusion"],
                "腹水": ["ascites"],
                "水肿": ["edema"],
                "脱水": ["dehydration"],
                "营养不良": ["malnutrition"],
                "肥胖": ["obesity"],
                "消瘦": ["emaciation"],
                "恶病质": ["cachexia"],
                "寒战": ["chills"],
                "盗汗": ["night sweats"],
                "乏力": ["asthenia"],
                "虚弱": ["weakness"],
                "疲劳": ["tiredness"],
                "嗜睡": ["somnolence"],
                "昏睡": ["stupor"],
                "昏迷": ["coma"],
                "意识障碍": ["consciousness disturbance"],
                "谵妄": ["delirium"],
                "精神错乱": ["mental confusion"],
                "记忆力障碍": ["memory disorder"],
                "注意力障碍": ["attention disorder"],
                "思维障碍": ["thought disorder"],
                "情绪障碍": ["mood disorder"],
                "焦虑障碍": ["anxiety disorder"],
                "抑郁障碍": ["depressive disorder"],
                "躁狂": ["mania"],
                "幻觉": ["hallucination"],
                "妄想": ["delusion"],
                "强迫观念": ["obsession"],
                "强迫行为": ["compulsion"],
                "自杀意念": ["suicidal ideation"],
                "自杀企图": ["suicidal attempt"],
                "性功能障碍": ["sexual dysfunction"],
                "性欲减退": ["decreased libido"],
                "勃起功能障碍": ["erectile dysfunction"],
                "射精障碍": ["ejaculatory dysfunction"],
                "月经紊乱": ["menstrual disorder"],
                "闭经": ["amenorrhea"],
                "异常子宫出血": ["abnormal uterine bleeding"],
                "痛经": ["dysmenorrhea"],
                "更年期综合征": ["menopausal syndrome"],
                "乳房胀痛": ["breast tenderness"],
                "乳头溢液": ["nipple discharge"],
                "阴道干涩": ["vaginal dryness"],
                "性交疼痛": ["dyspareunia"],
                "不孕": ["infertility"],
                "流产": ["abortion"],
                "早产": ["preterm birth"],
                "过期妊娠": ["post-term pregnancy"],
                "胎儿窘迫": ["fetal distress"],
                "胎膜早破": ["premature rupture of membranes"],
                "胎盘早剥": ["placental abruption"],
                "前置胎盘": ["placenta previa"],
                "产后出血": ["postpartum hemorrhage"],
                "产褥感染": ["puerperal infection"],
                "新生儿窒息": ["neonatal asphyxia"],
                "新生儿黄疸": ["neonatal jaundice"],
                "新生儿肺炎": ["neonatal pneumonia"],
                "新生儿败血症": ["neonatal sepsis"],
                "先天性畸形": ["congenital malformation"],
                "发育迟缓": ["developmental delay"],
                "智力低下": ["mental retardation"],
                "学习障碍": ["learning disorder"],
                "语言障碍": ["language disorder"],
                "言语障碍": ["speech disorder"],
                "口吃": ["stuttering"],
                "听力障碍": ["hearing impairment"],
                "视力障碍": ["visual impairment"],
                "运动障碍": ["motor disorder"],
                "协调障碍": ["coordination disorder"],
                "平衡障碍": ["balance disorder"],
                "姿势异常": ["postural abnormality"],
                "步态异常": ["gait abnormality"],
                "肌肉痉挛": ["muscle spasm"],
                "肌肉抽搐": ["muscle twitch"],
                "肌肉僵硬": ["muscle rigidity"],
                "肌肉无力": ["muscle weakness"],
                "肌肉萎缩": ["muscle atrophy"],
                "关节活动受限": ["limited joint movement"],
                "关节畸形": ["joint deformity"],
                "关节肿胀": ["joint swelling"],
                "关节疼痛": ["joint pain"],
                "骨痛": ["bone pain"],
                "骨折": ["fracture"],
                "脱位": ["dislocation"],
                "扭伤": ["sprain"],
                "拉伤": ["strain"],
                "挫伤": ["contusion"],
                "撕裂伤": ["laceration"],
                "穿刺伤": ["puncture wound"],
                "烧伤": ["burn"],
                "冻伤": ["frostbite"],
                "电击伤": ["electrical injury"],
                "溺水": ["drowning"],
                "窒息": ["asphyxia"],
                "中毒": ["poisoning"],
                "过敏反应": ["allergic reaction"],
                "休克": ["shock"],
            },
            "Drug": {
                "阿司匹林": ["乙酰水杨酸", "aspirin", "拜阿司匹林", "肠溶片"],
                "布洛芬": ["ibuprofen", "芬必得", "美林", "安瑞克"],
                "青霉素": ["盘尼西林", "penicillin", "青霉素G"],
                "阿莫西林": ["amoxicillin", "阿莫仙"],
                "头孢氨苄": ["cephalexin", "先锋霉素IV"],
                "头孢拉定": ["cefradine", "先锋霉素VI"],
                "头孢呋辛": ["cefuroxime", "西力欣"],
                "头孢曲松": ["ceftriaxone", "罗氏芬", "菌必治"],
                "红霉素": ["erythromycin"],
                "阿奇霉素": ["azithromycin", "希舒美"],
                "克拉霉素": ["clarithromycin", "克拉仙"],
                "四环素": ["tetracycline"],
                "多西环素": ["doxycycline", "强力霉素"],
                "左氧氟沙星": ["levofloxacin", "可乐必妥"],
                "环丙沙星": ["ciprofloxacin", "西普乐"],
                "诺氟沙星": ["norfloxacin", "氟哌酸"],
                "甲硝唑": ["metronidazole", "灭滴灵"],
                "替硝唑": ["tinidazole"],
                "氯霉素": ["chloramphenicol"],
                "万古霉素": ["vancomycin", "稳可信"],
                "利福平": ["rifampicin", "RFP"],
                "异烟肼": ["isoniazid", "雷米封", "INH"],
                "吡嗪酰胺": ["pyrazinamide", "PZA"],
                "乙胺丁醇": ["ethambutol", "EMB"],
                "胰岛素": ["insulin", "优泌林", "诺和灵", "来得时"],
                "二甲双胍": ["metformin", "格华止"],
                "格列齐特": ["gliclazide", "达美康"],
                "格列美脲": ["glimepiride", "亚莫利"],
                "瑞格列奈": ["repaglinide", "诺和龙"],
                "阿卡波糖": ["acarbose", "拜唐苹"],
                "硝苯地平": ["nifedipine", "心痛定", "拜新同"],
                "氨氯地平": ["amlodipine", "络活喜"],
                "左旋氨氯地平": ["levamlodipine", "施慧达"],
                "非洛地平": ["felodipine", "波依定"],
                "拉西地平": ["lacidipine", "乐息平"],
                "尼莫地平": ["nimodipine", "尼莫通"],
                "地尔硫卓": ["diltiazem", "合心爽"],
                "维拉帕米": ["verapamil", "异搏定"],
                "美托洛尔": ["metoprolol", "倍他乐克"],
                "比索洛尔": ["bisoprolol", "康忻"],
                "阿替洛尔": ["atenolol"],
                "卡托普利": ["captopril", "开博通"],
                "依那普利": ["enalapril", "悦宁定"],
                "贝那普利": ["benazepril", "洛汀新"],
                "赖诺普利": ["lisinopril", "捷赐瑞"],
                "雷米普利": ["ramipril", "瑞泰"],
                "厄贝沙坦": ["irbesartan", "安博维"],
                "缬沙坦": ["valsartan", "代文"],
                "氯沙坦": ["losartan", "科素亚"],
                "替米沙坦": ["telmisartan", "美卡素"],
                "氢氯噻嗪": ["hydrochlorothiazide", "双氢克尿噻"],
                "呋塞米": ["furosemide", "速尿"],
                "螺内酯": ["spironolactone", "安体舒通"],
                "氨苯蝶啶": ["triamterene"],
                "硝酸甘油": ["nitroglycerin"],
                "单硝酸异山梨酯": ["isosorbide mononitrate", "鲁南欣康"],
                "硝酸异山梨酯": ["isosorbide dinitrate", "消心痛"],
                "肝素": ["heparin"],
                "低分子肝素": ["low molecular weight heparin", "LMWH", "速碧林", "克赛"],
                "华法林": ["warfarin", "华法令"],
                "氯吡格雷": ["clopidogrel", "波立维", "泰嘉"],
                "替格瑞洛": ["ticagrelor", "倍林达"],
                "阿托伐他汀": ["atorvastatin", "立普妥"],
                "瑞舒伐他汀": ["rosuvastatin", "可定"],
                "辛伐他汀": ["simvastatin", "舒降之"],
                "普伐他汀": ["pravastatin", "普拉固"],
                "氟伐他汀": ["fluvastatin", "来适可"],
                "氨茶碱": ["aminophylline"],
                "沙丁胺醇": ["salbutamol", "舒喘灵", "万托林"],
                "特布他林": ["terbutaline", "博利康尼"],
                "布地奈德": ["budesonide", "普米克"],
                "丙酸氟替卡松": ["fluticasone", "辅舒良", "舒利迭"],
                "孟鲁司特": ["montelukast", "顺尔宁"],
                "氨溴索": ["ambroxol", "沐舒坦"],
                "乙酰半胱氨酸": ["acetylcysteine", "富露施"],
                "奥美拉唑": ["omeprazole", "洛赛克"],
                "兰索拉唑": ["lansoprazole", "达克普隆"],
                "泮托拉唑": ["pantoprazole", "潘妥洛克"],
                "雷贝拉唑": ["rabeprazole", "波利特"],
                "法莫替丁": ["famotidine", "高舒达"],
                "雷尼替丁": ["ranitidine", "善胃得"],
                "西咪替丁": ["cimetidine", "泰胃美"],
                "铝碳酸镁": ["hydrotalcite", "达喜"],
                "氢氧化铝": ["aluminum hydroxide"],
                "枸橼酸铋钾": ["bismuth citrate", "丽珠得乐"],
                "硫糖铝": ["sucralfate"],
                "多潘立酮": ["domperidone", "吗丁啉"],
                "莫沙必利": ["mosapride", "加斯清"],
                "伊托必利": ["itopride", "为力苏"],
                "乳果糖": ["lactulose", "杜密克"],
                "聚乙二醇": ["polyethylene glycol", "福松"],
                "开塞露": ["glycerin enema"],
                "蒙脱石散": ["smectite", "思密达"],
                "洛哌丁胺": ["loperamide", "易蒙停"],
                "硫唑嘌呤": ["azathioprine"],
                "环磷酰胺": ["cyclophosphamide", "CTX"],
                "甲氨蝶呤": ["methotrexate", "MTX"],
                "环孢素": ["cyclosporine", "CsA"],
                "他克莫司": ["tacrolimus", "FK506", "普乐可复"],
                "泼尼松": ["prednisone", "强的松"],
                "地塞米松": ["dexamethasone", "氟美松"],
                "甲泼尼龙": ["methylprednisolone", "美卓乐"],
                "氢化可的松": ["hydrocortisone"],
                "甲状腺素": ["levothyroxine", "优甲乐"],
                "甲巯咪唑": ["methimazole", "他巴唑"],
                "丙硫氧嘧啶": ["propylthiouracil", "PTU"],
            },
            "Anatomy": {
                "心脏": ["心", "heart", "心肌", "cardiac"],
                "肺": ["肺部", "lungs", "肺脏", "pulmonary"],
                "肝脏": ["肝", "liver", "hepatic"],
                "肾脏": ["肾", "kidney", "renal"],
                "大脑": ["脑", "brain", "cerebral"],
                "小脑": ["cerebellum"],
                "脑干": ["brainstem"],
                "脊髓": ["spinal cord"],
                "胃": ["胃部", "stomach", "gastric"],
                "肠道": ["肠", "intestine", "bowel"],
                "小肠": ["small intestine"],
                "大肠": ["large intestine", "colon"],
                "直肠": ["rectum"],
                "结肠": ["colon"],
                "阑尾": ["appendix"],
                "胆囊": ["gallbladder"],
                "胆管": ["bile duct"],
                "胰腺": ["pancreas", "胰"],
                "脾脏": ["spleen", "脾"],
                "胸腺": ["thymus"],
                "淋巴结": ["lymph node"],
                "骨骼": ["bone", "骨骼系统"],
                "关节": ["joint"],
                "肌肉": ["muscle"],
                "血管": ["blood vessel", "vascular"],
                "动脉": ["artery"],
                "静脉": ["vein"],
                "毛细血管": ["capillary"],
                "皮肤": ["skin", "cutaneous"],
                "毛发": ["hair"],
                "指甲": ["nail"],
                "眼睛": ["eye", "ocular"],
                "耳朵": ["ear", "auditory"],
                "鼻子": ["nose", "nasal"],
                "嘴巴": ["mouth", "oral"],
                "牙齿": ["tooth", "dental"],
                "舌头": ["tongue"],
                "咽喉": ["throat", "pharynx", "larynx"],
                "气管": ["trachea", "windpipe"],
                "支气管": ["bronchus", "bronchi"],
                "食道": ["esophagus", "食管"],
                "输尿管": ["ureter"],
                "膀胱": ["bladder"],
                "尿道": ["urethra"],
                "子宫": ["uterus", "womb"],
                "卵巢": ["ovary"],
                "输卵管": ["fallopian tube"],
                "阴道": ["vagina"],
                "前列腺": ["prostate"],
                "睾丸": ["testis", "testicle"],
                "附睾": ["epididymis"],
                "阴茎": ["penis"],
                "乳房": ["breast", "mammary"],
                "甲状腺": ["thyroid"],
                "甲状旁腺": ["parathyroid"],
                "肾上腺": ["adrenal gland"],
                "垂体": ["pituitary gland"],
                "松果体": ["pineal gland"],
                "扁桃体": ["tonsil"],
                "腺样体": ["adenoid"],
                "鼻窦": ["sinus"],
                "椎间盘": ["intervertebral disc"],
                "神经根": ["nerve root"],
                "神经节": ["ganglion"],
                "神经": ["nerve"],
                "肌腱": ["tendon"],
                "韧带": ["ligament"],
                "筋膜": ["fascia"],
                "滑膜": ["synovium"],
                "软骨": ["cartilage"],
                "骨髓": ["bone marrow"],
            },
            "Department": {
                "内科": ["internal medicine", "普内科"],
                "外科": ["surgery", "普通外科"],
                "急诊科": ["急诊", "emergency", "ER"],
                "妇产科": ["妇科", "obstetrics and gynecology", "OB/GYN"],
                "儿科": ["pediatrics", "小儿科"],
                "神经科": ["神经内科", "neurology"],
                "心内科": ["心血管内科", "cardiology"],
                "消化内科": ["gastroenterology", "消化科"],
                "呼吸内科": ["pulmonology", "respiratory", "呼吸科"],
                "肾内科": ["nephrology", "肾脏内科"],
                "内分泌科": ["endocrinology"],
                "血液科": ["hematology"],
                "风湿科": ["rheumatology", "风湿免疫科"],
                "感染科": ["infectious disease", "传染科"],
                "肝病科": ["hepatology"],
                "骨科": ["orthopedics", "bone surgery"],
                "胸外科": ["thoracic surgery"],
                "心外科": ["cardiac surgery", "心脏外科"],
                "神经外科": ["neurosurgery"],
                "泌尿外科": ["urology"],
                "普外科": ["general surgery"],
                "乳腺外科": ["breast surgery"],
                "肝胆外科": ["hepatobiliary surgery"],
                "胃肠外科": ["gastrointestinal surgery"],
                "血管外科": ["vascular surgery"],
                "烧伤科": ["burn unit"],
                "整形外科": ["plastic surgery"],
                "眼科": ["ophthalmology"],
                "耳鼻喉科": ["ENT", "otolaryngology"],
                "口腔科": ["dentistry", "口腔医学"],
                "皮肤科": ["dermatology"],
                "精神科": ["psychiatry", "精神病科"],
                "心理科": ["psychology", "心理咨询"],
                "康复科": ["rehabilitation", "康复医学"],
                "麻醉科": ["anesthesiology"],
                "疼痛科": ["pain management"],
                "重症医学科": ["ICU", "critical care"],
                "放射科": ["radiology", "影像科"],
                "超声科": ["ultrasound"],
                "检验科": ["laboratory", "化验科"],
                "病理科": ["pathology"],
                "药剂科": ["pharmacy", "药房"],
                "营养科": ["nutrition"],
                "输血科": ["transfusion medicine"],
                "预防保健科": ["preventive medicine"],
            },
            "Treatment": {
                "手术": ["operation", "surgery", "外科手术"],
                "药物治疗": ["pharmacotherapy", "药物疗法", "化疗"],
                "放射治疗": ["radiotherapy", "放疗"],
                "化疗": ["chemotherapy", "化学治疗"],
                "免疫治疗": ["immunotherapy", "生物治疗"],
                "靶向治疗": ["targeted therapy"],
                "干细胞移植": ["stem cell transplant"],
                "骨髓移植": ["bone marrow transplant"],
                "物理治疗": ["physical therapy", "理疗"],
                "康复治疗": ["rehabilitation"],
                "针灸": ["acupuncture"],
                "按摩": ["massage", "推拿"],
                "中药治疗": ["Chinese medicine", "中医药"],
                "手术切除": ["resection"],
                "搭桥手术": ["bypass surgery", "冠状动脉搭桥"],
                "置换手术": ["replacement surgery", "关节置换"],
                "介入治疗": ["interventional therapy"],
                "内镜治疗": ["endoscopic therapy"],
                "激光治疗": ["laser therapy"],
                "冷冻治疗": ["cryotherapy"],
                "电疗": ["electrotherapy"],
                "磁疗": ["magnetic therapy"],
                "光疗": ["phototherapy"],
                "热疗": ["hyperthermia"],
                "氧疗": ["oxygen therapy"],
                "透析": ["dialysis", "血液透析", "腹膜透析"],
                "输液": ["intravenous therapy", "静脉输液"],
                "输血": ["blood transfusion"],
                "营养支持": ["nutritional support"],
                "心理治疗": ["psychotherapy", "心理咨询"],
                "认知行为治疗": ["CBT", "认知行为疗法"],
                "催眠治疗": ["hypnotherapy"],
                "脱敏治疗": ["desensitization", "免疫脱敏"],
                "疫苗接种": ["vaccination", "immunization"],
                "基因治疗": ["gene therapy"],
                "细胞治疗": ["cell therapy"],
                "康复训练": ["rehabilitation training"],
                "职业治疗": ["occupational therapy"],
                "语言治疗": ["speech therapy"],
                "音乐治疗": ["music therapy"],
                "艺术治疗": ["art therapy"],
                "运动疗法": ["exercise therapy"],
                "饮食疗法": ["diet therapy", "食疗"],
            },
            "DiagnosticCriteria": {
                "ACR标准": ["美国风湿病学会标准"],
                "WHO标准": ["世界卫生组织标准"],
                "中华医学会标准": ["中国标准", "国内标准"],
                "DSM-5": ["精神疾病诊断与统计手册第五版"],
                "ICD-10标准": ["国际疾病分类第十版标准"],
                "临床诊断标准": ["临床标准"],
                "影像学诊断标准": ["影像标准"],
                "实验室诊断标准": ["化验标准"],
                "病理诊断标准": ["病理标准"],
                "诊断指南": ["诊疗指南", "临床指南"],
            },
            "Prognosis": {
                "良好": ["预后好", "恢复良好", "治愈"],
                "一般": ["预后中等", "恢复一般"],
                "不良": ["预后差", "恢复差", "病情危重"],
                "不确定": ["预后不明", "不确定"],
                "复发风险": ["复发可能性", "再次发作"],
                "生存率": ["存活率", "生存概率"],
                "并发症风险": ["并发症可能性"],
            },
            "RiskFactor": {
                "年龄": ["年龄因素"],
                "性别": ["性别因素"],
                "遗传": ["家族史", "遗传因素", "基因"],
                "吸烟": ["吸烟史", "烟草暴露"],
                "饮酒": ["饮酒史", "酒精摄入"],
                "肥胖": ["超重", "BMI过高"],
                "高血压": ["血压高"],
                "糖尿病": ["高血糖"],
                "高血脂": ["血脂异常"],
                "缺乏运动": ["久坐", "不运动"],
                "不良饮食": ["饮食不当", "不健康饮食"],
                "压力": ["精神压力", "心理压力"],
                "睡眠不足": ["失眠", "睡眠障碍"],
                "环境因素": ["环境污染", "职业暴露"],
                "病毒感染": ["病毒", "感染史"],
                "细菌感染": ["细菌", "感染"],
            },
            "Examination": {
                "血常规": ["blood count", "complete blood count", "CBC"],
                "尿常规": ["urinalysis", "尿液检查"],
                "大便常规": ["stool analysis", "粪便检查"],
                "肝功能": ["liver function", "hepatic function"],
                "肾功能": ["renal function", "kidney function"],
                "血糖": ["blood glucose", "glucose test"],
                "血脂": ["lipid profile", "血脂分析"],
                "电解质": ["electrolytes", "电解质检查"],
                "凝血功能": ["coagulation function", "凝血检查"],
                "激素检查": ["hormone test", "内分泌检查"],
                "甲状腺功能": ["thyroid function"],
                "肿瘤标志物": ["tumor marker"],
                "心电图": ["ECG", "EKG", "electrocardiogram"],
                "超声": ["ultrasound", "B超", "彩超"],
                "CT": ["computed tomography", "计算机断层扫描"],
                "MRI": ["magnetic resonance imaging", "磁共振成像"],
                "X光": ["X-ray", "放射线检查"],
                "PET": ["positron emission tomography", "正电子发射断层扫描"],
                "PET-CT": ["PET computed tomography"],
                "胃镜": ["gastroscopy", "上消化道内镜"],
                "肠镜": ["colonoscopy", "结肠镜"],
                "支气管镜": ["bronchoscopy"],
                "腹腔镜": ["laparoscopy"],
                "宫腔镜": ["hysteroscopy"],
                "关节镜": ["arthroscopy"],
                "病理检查": ["pathological examination", "活检"],
                "细菌培养": ["bacterial culture"],
                "病毒检测": ["viral test"],
                "核酸检测": ["nucleic acid test", "PCR"],
                "抗体检测": ["antibody test"],
                "过敏原检测": ["allergen test"],
                "肺功能检查": ["pulmonary function test"],
                "心电图": ["electrocardiogram", "ECG"],
                "动态心电图": ["Holter monitor", "24小时心电图"],
                "心脏彩超": ["echocardiography", "心脏超声"],
                "血管超声": ["vascular ultrasound"],
                "腹部超声": ["abdominal ultrasound"],
                "妇科超声": ["gynecological ultrasound"],
                "产科超声": ["obstetric ultrasound"],
                "乳腺超声": ["breast ultrasound"],
                "甲状腺超声": ["thyroid ultrasound"],
                "头颅CT": ["head CT", "脑部CT"],
                "头颅MRI": ["head MRI", "脑部MRI"],
                "脊柱CT": ["spine CT"],
                "脊柱MRI": ["spine MRI"],
                "全身CT": ["whole body CT"],
                "全身MRI": ["whole body MRI"],
                "骨骼X光": ["bone X-ray"],
                "胸部X光": ["chest X-ray"],
                "腹部X光": ["abdominal X-ray"],
                "钡餐造影": ["barium meal", "消化道造影"],
                "钡灌肠": ["barium enema"],
                "血管造影": ["angiography"],
                "冠状动脉造影": ["coronary angiography"],
                "脑血管造影": ["cerebral angiography"],
                "骨髓穿刺": ["bone marrow aspiration"],
                "腰椎穿刺": ["lumbar puncture", "腰穿"],
                "胸腔穿刺": ["thoracentesis"],
                "腹腔穿刺": ["paracentesis"],
                "心包穿刺": ["pericardiocentesis"],
                "关节穿刺": ["joint aspiration"],
                "羊水穿刺": ["amniocentesis"],
                "绒毛膜穿刺": ["chorionic villus sampling"],
                "基因检测": ["genetic testing", "DNA testing"],
                "染色体分析": ["chromosome analysis"],
                "免疫功能检查": ["immune function test"],
                "自身抗体检测": ["autoantibody test"],
                "血沉": ["erythrocyte sedimentation rate", "ESR"],
                "C反应蛋白": ["C-reactive protein", "CRP"],
                "类风湿因子": ["rheumatoid factor", "RF"],
                "抗核抗体": ["antinuclear antibody", "ANA"],
                "补体检查": ["complement test"],
                "病毒学检查": ["virological test"],
                "细菌学检查": ["bacteriological test"],
                "真菌学检查": ["mycological test"],
                "寄生虫检查": ["parasitological test"],
                "细胞学检查": ["cytological examination"],
                "组织学检查": ["histological examination"],
                "免疫组织化学": ["immunohistochemistry", "IHC"],
                "流式细胞术": ["flow cytometry"],
                "聚合酶链反应": ["polymerase chain reaction", "PCR"],
                "酶联免疫吸附试验": ["enzyme-linked immunosorbent assay", "ELISA"],
                "放射免疫分析": ["radioimmunoassay", "RIA"],
                "化学发光免疫分析": ["chemiluminescence immunoassay", "CLIA"],
                "质谱分析": ["mass spectrometry"],
                "高效液相色谱": ["high-performance liquid chromatography", "HPLC"],
                "气相色谱": ["gas chromatography", "GC"],
                "原子吸收光谱": ["atomic absorption spectroscopy"],
                "电解质分析": ["electrolyte analysis"],
                "血气分析": ["blood gas analysis"],
                "凝血酶原时间": ["prothrombin time", "PT"],
                "活化部分凝血活酶时间": ["activated partial thromboplastin time", "APTT"],
                "纤维蛋白原": ["fibrinogen"],
                "D-二聚体": ["D-dimer"],
                "血小板功能检查": ["platelet function test"],
                "血型鉴定": ["blood typing"],
                "交叉配血": ["crossmatching"],
                "输血前检查": ["pre-transfusion testing"],
                "肝功能试验": ["liver function tests"],
                "肾功能试验": ["renal function tests"],
                "心肌酶谱": ["cardiac enzyme profile"],
                "肌钙蛋白": ["cardiac troponin"],
                "脑钠肽": ["brain natriuretic peptide", "BNP"],
                "血糖测定": ["blood glucose measurement"],
                "糖化血红蛋白": ["glycated hemoglobin", "HbA1c"],
                "糖化白蛋白": ["glycated albumin"],
                "胰岛素测定": ["insulin measurement"],
                "C肽测定": ["C-peptide measurement"],
                "血脂测定": ["lipid measurement"],
                "脂蛋白分析": ["lipoprotein analysis"],
                "甲状腺激素": ["thyroid hormones"],
                "促甲状腺激素": ["thyroid-stimulating hormone", "TSH"],
                "性激素": ["sex hormones"],
                "皮质醇": ["cortisol"],
                "肾上腺素": ["epinephrine"],
                "去甲肾上腺素": ["norepinephrine"],
                "生长激素": ["growth hormone"],
                "泌乳素": ["prolactin"],
                "卵泡刺激素": ["follicle-stimulating hormone", "FSH"],
                "黄体生成素": ["luteinizing hormone", "LH"],
                "孕酮": ["progesterone"],
                "雌二醇": ["estradiol"],
                "睾酮": ["testosterone"],
                "肿瘤标志物": ["tumor markers"],
                "癌胚抗原": ["carcinoembryonic antigen", "CEA"],
                "甲胎蛋白": ["alpha-fetoprotein", "AFP"],
                "CA19-9": ["carbohydrate antigen 19-9"],
                "CA125": ["carbohydrate antigen 125"],
                "PSA": ["prostate-specific antigen"],
                "CA15-3": ["carbohydrate antigen 15-3"],
                "SCC": ["squamous cell carcinoma antigen"],
                "NSE": ["neuron-specific enolase"],
                "CYFRA21-1": ["cytokeratin 19 fragment"],
                "胃蛋白酶原": ["pepsinogen"],
                "幽门螺杆菌检测": ["Helicobacter pylori test"],
                "粪便隐血试验": ["fecal occult blood test"],
                "尿液培养": ["urine culture"],
                "尿流率测定": ["urine flow rate"],
                "残余尿测定": ["residual urine measurement"],
                "膀胱镜检查": ["cystoscopy"],
                "输尿管镜检查": ["ureteroscopy"],
                "前列腺穿刺": ["prostate biopsy"],
                "宫颈涂片": ["Pap smear"],
                "HPV检测": ["human papillomavirus test"],
                "阴道分泌物检查": ["vaginal discharge examination"],
                "输卵管造影": ["hysterosalpingography"],
                "宫腔镜检查": ["hysteroscopy"],
                "腹腔镜检查": ["laparoscopy"],
                "乳腺X线摄影": ["mammography"],
                "乳腺MRI": ["breast MRI"],
                "甲状腺穿刺": ["thyroid biopsy"],
                "骨密度测定": ["bone mineral density", "BMD"],
                "关节X线": ["joint X-ray"],
                "关节MRI": ["joint MRI"],
                "肌电图": ["electromyography", "EMG"],
                "神经传导速度": ["nerve conduction velocity", "NCV"],
                "诱发电位": ["evoked potentials"],
                "脑电图": ["electroencephalogram", "EEG"],
                "睡眠监测": ["polysomnography", "PSG"],
                "肺功能试验": ["pulmonary function tests"],
                "支气管激发试验": ["bronchial provocation test"],
                "支气管舒张试验": ["bronchodilator test"],
                "弥散功能测定": ["diffusion capacity"],
                "动脉血气分析": ["arterial blood gas analysis"],
                "六分钟步行试验": ["six-minute walk test"],
                "心电图运动试验": ["exercise stress test"],
                "心脏电生理检查": ["electrophysiological study"],
                "冠状动脉CTA": ["coronary CTA"],
                "心脏MRI": ["cardiac MRI"],
                "主动脉CTA": ["aortic CTA"],
                "下肢动脉CTA": ["lower extremity CTA"],
                "下肢静脉CTV": ["lower extremity CTV"],
                "头颅MRA": ["head MRA"],
                "颈部MRA": ["neck MRA"],
                "脑血管CTA": ["cerebral CTA"],
                "脊髓造影": ["myelography"],
                "椎间盘造影": ["discography"],
                "核素扫描": ["nuclear scan"],
                "骨扫描": ["bone scan"],
                "心肌灌注显像": ["myocardial perfusion imaging"],
                "甲状腺扫描": ["thyroid scan"],
                "肾动态显像": ["renal scintigraphy"],
                "肺灌注显像": ["lung perfusion scan"],
                "肺通气显像": ["lung ventilation scan"],
                "PET-CT": ["PET-CT"],
                "PET-MRI": ["PET-MRI"],
                "内镜超声": ["endoscopic ultrasound", "EUS"],
                "胶囊内镜": ["capsule endoscopy"],
                "双气囊小肠镜": ["double-balloon enteroscopy"],
                "共聚焦内镜": ["confocal endoscopy"],
                "窄带成像": ["narrow band imaging", "NBI"],
                "放大内镜": ["magnifying endoscopy"],
                "超声内镜": ["endoscopic ultrasound"],
                "介入治疗": ["interventional therapy"],
                "血管介入": ["vascular intervention"],
                "神经介入": ["neurointervention"],
                "肿瘤介入": ["oncologic intervention"],
                "超声引导穿刺": ["ultrasound-guided biopsy"],
                "CT引导穿刺": ["CT-guided biopsy"],
                "MRI引导穿刺": ["MRI-guided biopsy"],
                "基因测序": ["next-generation sequencing", "NGS"],
                "全外显子测序": ["whole exome sequencing", "WES"],
                "全基因组测序": ["whole genome sequencing", "WGS"],
                "RNA测序": ["RNA sequencing", "RNA-seq"],
                "甲基化检测": ["methylation testing"],
                "染色体微阵列分析": ["chromosomal microarray analysis", "CMA"],
                "荧光原位杂交": ["fluorescence in situ hybridization", "FISH"],
                "比较基因组杂交": ["comparative genomic hybridization", "CGH"],
                "聚合酶链反应": ["polymerase chain reaction", "PCR"],
                "实时荧光定量PCR": ["quantitative real-time PCR", "qPCR"],
                "逆转录PCR": ["reverse transcription PCR", "RT-PCR"],
                "数字PCR": ["digital PCR", "dPCR"],
                "酶联免疫吸附试验": ["enzyme-linked immunosorbent assay", "ELISA"],
                "免疫印迹": ["Western blot"],
                "免疫沉淀": ["immunoprecipitation"],
                "流式细胞术": ["flow cytometry"],
                "细胞培养": ["cell culture"],
                "细菌培养": ["bacterial culture"],
                "真菌培养": ["fungal culture"],
                "病毒培养": ["viral culture"],
                "药敏试验": ["antimicrobial susceptibility testing"],
                "血液培养": ["blood culture"],
                "尿液培养": ["urine culture"],
                "痰液培养": ["sputum culture"],
                "脑脊液培养": ["cerebrospinal fluid culture"],
                "腹水培养": ["ascites culture"],
                "胸水培养": ["pleural fluid culture"],
                "组织培养": ["tissue culture"],
                "支原体培养": ["mycoplasma culture"],
                "衣原体培养": ["chlamydia culture"],
                "螺旋体培养": ["spirochete culture"],
                "寄生虫培养": ["parasite culture"],
                "核酸扩增试验": ["nucleic acid amplification test", "NAAT"],
                "核酸测序": ["nucleic acid sequencing"],
                "蛋白质组学分析": ["proteomics analysis"],
                "代谢组学分析": ["metabolomics analysis"],
                "脂质组学分析": ["lipidomics analysis"],
                "糖组学分析": ["glycomics analysis"],
                "表观遗传学分析": ["epigenetics analysis"],
                "生物信息学分析": ["bioinformatics analysis"],
                "数据分析": ["data analysis"],
                "统计分析": ["statistical analysis"],
                "机器学习": ["machine learning"],
                "人工智能": ["artificial intelligence"],
                "深度学习": ["deep learning"],
                "自然语言处理": ["natural language processing"],
                "图像识别": ["image recognition"],
                "语音识别": ["speech recognition"],
                "数据挖掘": ["data mining"],
                "知识发现": ["knowledge discovery"],
                "大数据分析": ["big data analysis"],
                "云计算": ["cloud computing"],
                "边缘计算": ["edge computing"],
                "物联网": ["internet of things"],
                "区块链": ["blockchain"],
                "虚拟现实": ["virtual reality"],
                "增强现实": ["augmented reality"],
                "混合现实": ["mixed reality"],
                "数字孪生": ["digital twin"],
                "远程医疗": ["telemedicine"],
                "移动医疗": ["mobile health", "mHealth"],
                "智慧医疗": ["smart healthcare"],
                "精准医疗": ["precision medicine"],
                "个性化医疗": ["personalized medicine"],
                "预测医疗": ["predictive medicine"],
                "预防医疗": ["preventive medicine"],
                "康复医疗": ["rehabilitation medicine"],
                "老年医学": ["geriatric medicine"],
                "急诊医学": ["emergency medicine"],
                "重症医学": ["critical care medicine"],
                "麻醉医学": ["anesthesiology"],
                "疼痛医学": ["pain medicine"],
                "介入医学": ["interventional medicine"],
                "放射医学": ["radiology"],
                "超声医学": ["ultrasound medicine"],
                "核医学": ["nuclear medicine"],
                "病理学": ["pathology"],
                "检验医学": ["laboratory medicine"],
                "药学": ["pharmacy"],
                "护理学": ["nursing"],
                "医学教育": ["medical education"],
                "医学研究": ["medical research"],
                "医学信息学": ["medical informatics"],
                "生物医学工程": ["biomedical engineering"],
                "卫生政策": ["health policy"],
                "卫生管理": ["health management"],
                "公共卫生": ["public health"],
                "流行病学": ["epidemiology"],
                "环境卫生": ["environmental health"],
                "职业卫生": ["occupational health"],
                "营养与食品卫生": ["nutrition and food hygiene"],
                "儿少卫生与妇幼保健": ["maternal and child health"],
                "卫生毒理学": ["health toxicology"],
                "卫生统计学": ["health statistics"],
                "医学伦理学": ["medical ethics"],
                "医学法学": ["medical law"],
                "医学社会学": ["medical sociology"],
                "医学人类学": ["medical anthropology"],
                "医学心理学": ["medical psychology"],
                "医学美学": ["medical aesthetics"],
                "医学哲学": ["medical philosophy"],
                "医学史": ["medical history"],
                "医学地理学": ["medical geography"],
                "医学经济学": ["medical economics"],
                "医学管理学": ["medical management"],
                "医学教育学": ["medical education"],
                "医学科研方法学": ["medical research methodology"],
                "医学统计学": ["medical statistics"],
                "医学信息检索": ["medical information retrieval"],
                "医学论文写作": ["medical writing"],
                "医学翻译": ["medical translation"],
                "医学编辑": ["medical editing"],
                "医学出版": ["medical publishing"],
                "医学科普": ["medical popularization"],
                "医学传播": ["medical communication"],
                "医学营销": ["medical marketing"],
                "医学公关": ["medical public relations"],
                "医学广告": ["medical advertising"],
                "医学品牌": ["medical branding"],
                "医学电商": ["medical e-commerce"],
                "医学物流": ["medical logistics"],
                "医学供应链": ["medical supply chain"],
                "医学设备": ["medical equipment"],
                "医学器械": ["medical devices"],
                "医学耗材": ["medical supplies"],
                "医学软件": ["medical software"],
                "医学硬件": ["medical hardware"],
                "医学人工智能": ["medical artificial intelligence"],
                "医学机器人": ["medical robotics"],
                "医学3D打印": ["medical 3D printing"],
                "医学虚拟现实": ["medical virtual reality"],
                "医学增强现实": ["medical augmented reality"],
                "医学物联网": ["medical internet of things"],
                "医学大数据": ["medical big data"],
                "医学云计算": ["medical cloud computing"],
                "医学区块链": ["medical blockchain"],
                "医学数字孪生": ["medical digital twin"],
                "医学元宇宙": ["medical metaverse"],
            },
        }

    def _load_abbreviation_map(self) -> Dict[str, str]:
        """加载医疗缩写映射表"""
        return {
            "HTN": "高血压",
            "BP": "血压",
            "DM": "糖尿病",
            "MI": "心肌梗死",
            "CVA": "脑梗死",
            "CHD": "冠心病",
            "CAD": "冠状动脉疾病",
            "COPD": "慢性阻塞性肺疾病",
            "TB": "肺结核",
            "AIDS": "艾滋病",
            "HIV": "人类免疫缺陷病毒",
            "RA": "类风湿关节炎",
            "SLE": "系统性红斑狼疮",
            "AS": "强直性脊柱炎",
            "OA": "骨关节炎",
            "PD": "帕金森病",
            "AD": "阿尔茨海默病",
            "MS": "多发性硬化",
            "ALS": "肌萎缩侧索硬化",
            "MG": "重症肌无力",
            "GBS": "吉兰-巴雷综合征",
            "PTSD": "创伤后应激障碍",
            "OCD": "强迫症",
            "ADHD": "注意缺陷多动障碍",
            "ASD": "自闭症谱系障碍",
            "UTI": "尿路感染",
            "IV": "静脉注射",
            "PO": "口服",
            "IM": "肌肉注射",
            "QD": "每日一次",
            "BID": "每日两次",
            "TID": "每日三次",
            "QID": "每日四次",
            "HS": "睡前",
            "AM": "上午",
            "PM": "下午",
            "AC": "饭前",
            "PC": "饭后",
            "PRN": "必要时",
            "STAT": "立即",
            "CBC": "血常规",
            "EKG": "心电图",
            "MRI": "磁共振成像",
            "CT": "计算机断层扫描",
            "PET": "正电子发射断层扫描",
            "XR": "X光检查",
            "US": "超声检查",
            "EEG": "脑电图",
            "EMG": "肌电图",
            "LP": "腰椎穿刺",
            "ABG": "动脉血气分析",
            "PFT": "肺功能检查",
            "BMI": "身体质量指数",
            "HR": "心率",
            "RR": "呼吸频率",
            "SPO2": "血氧饱和度",
            "WBC": "白细胞计数",
            "RBC": "红细胞计数",
            "HGB": "血红蛋白",
            "PLT": "血小板计数",
            "PT": "凝血酶原时间",
            "APTT": "活化部分凝血活酶时间",
            "INR": "国际标准化比值",
            "GLU": "血糖",
            "BUN": "血尿素氮",
            "CR": "肌酐",
            "ALT": "谷丙转氨酶",
            "AST": "谷草转氨酶",
            "ALP": "碱性磷酸酶",
            "GGT": "谷氨酰转肽酶",
            "TBIL": "总胆红素",
            "DBIL": "直接胆红素",
            "TP": "总蛋白",
            "ALB": "白蛋白",
            "LDH": "乳酸脱氢酶",
            "CK": "肌酸激酶",
            "CKMB": "肌酸激酶同工酶",
            "TNI": "肌钙蛋白I",
            "BNP": "脑钠肽",
            "CRP": "C反应蛋白",
            "ESR": "血沉",
            "RF": "类风湿因子",
            "ANA": "抗核抗体",
            "HBSAG": "乙肝表面抗原",
            "HCV": "丙肝病毒",
        }

    def _load_icd10_mapping(self) -> Dict[str, str]:
        """加载ICD-10疾病编码映射表 - 基于WHO官方ICD-10标准"""
        return {
            "高血压": "I10",
            "糖尿病": "E11",
            "2型糖尿病": "E11",
            "1型糖尿病": "E10",
            "肺炎": "J18",
            "冠心病": "I25",
            "心绞痛": "I20",
            "心肌梗死": "I21",
            "脑梗死": "I63",
            "脑出血": "I61",
            "蛛网膜下腔出血": "I60",
            "短暂性脑缺血发作": "G45",
            "帕金森病": "G20",
            "阿尔茨海默病": "G30",
            "抑郁症": "F32",
            "焦虑症": "F41",
            "精神分裂症": "F20",
            "哮喘": "J45",
            "慢性阻塞性肺疾病": "J44",
            "肺结核": "A15",
            "艾滋病": "B20",
            "胃癌": "C16",
            "肺癌": "C34",
            "肝癌": "C22",
            "乳腺癌": "C50",
            "结直肠癌": "C18-C20",
            "胰腺癌": "C25",
            "卵巢癌": "C56",
            "前列腺癌": "C61",
            "甲状腺癌": "C73",
            "白血病": "C91-C95",
            "淋巴瘤": "C81-C85",
            "胆结石": "K80",
            "胆囊炎": "K81",
            "阑尾炎": "K35",
            "胰腺炎": "K85",
            "胃炎": "K29",
            "消化性溃疡": "K25-K28",
            "肝硬化": "K74",
            "脂肪肝": "K76.0",
            "慢性肾脏病": "N18",
            "急性肾损伤": "N17",
            "肾病综合征": "N04",
            "贫血": "D50-D64",
            "缺铁性贫血": "D50",
            "再生障碍性贫血": "D61",
            "系统性红斑狼疮": "M32",
            "类风湿关节炎": "M05",
            "强直性脊柱炎": "M45",
            "痛风": "M10",
            "骨质疏松": "M81",
            "癫痫": "G40",
            "偏头痛": "G43",
            "带状疱疹": "B02",
            "流感": "J10-J11",
            "手足口病": "B08.4",
            "水痘": "B01",
            "麻疹": "B05",
            "风疹": "B06",
            "流行性腮腺炎": "B26",
            "猩红热": "A38",
            "百日咳": "A37",
            "病毒性肝炎": "B15-B19",
            "梅毒": "A50-A53",
            "淋病": "A54",
            "细菌性痢疾": "A09",
            "伤寒": "A01",
            "霍乱": "A00",
            "疟疾": "B50-B54",
            "登革热": "A90",
            "心律失常": "I47-I49",
            "心房颤动": "I48",
            "心力衰竭": "I50",
            "心肌炎": "I40",
            "心包炎": "I30",
            "胸腔积液": "J90",
            "气胸": "J93",
            "肺栓塞": "I26",
            "支气管扩张": "J47",
            "肺脓肿": "J85",
            "呼吸衰竭": "J96",
            "睡眠呼吸暂停": "G47.3",
            "鼻窦炎": "J01",
            "扁桃体炎": "J03",
            "中耳炎": "H65-H67",
            "青光眼": "H40",
            "白内障": "H25",
            "牙周病": "K05",
            "龋齿": "K02",
            "脂溢性皮炎": "L21",
            "湿疹": "L20",
            "银屑病": "L40",
            "荨麻疹": "L50",
            "痤疮": "L70",
            "脱发": "L63",
            "白癜风": "L80",
            "过敏性紫癜": "D69.0",
            "深静脉血栓": "I82",
            "多发性硬化": "G35",
            "肌萎缩侧索硬化": "G12.2",
            "重症肌无力": "G70",
            "吉兰-巴雷综合征": "G61",
            "腕管综合征": "G56.0",
            "三叉神经痛": "G50.0",
            "面神经麻痹": "G51.0",
            "双相情感障碍": "F31",
            "创伤后应激障碍": "F43.1",
            "强迫症": "F42",
            "注意缺陷多动障碍": "F90",
            "自闭症谱系障碍": "F84",
            "酒精使用障碍": "F10",
            "创伤性脑损伤": "S06",
            "脊髓损伤": "S14-S34",
            "败血症": "A41",
            "尿路感染": "N39",
            "脑膜炎": "G00-G03",
            "脑炎": "G04",
            "骨髓炎": "M86",
            "炎性肠病": "K50-K51",
            "克罗恩病": "K50",
            "溃疡性结肠炎": "K51",
            "肠易激综合征": "K58",
            "胃食管反流病": "K21",
            "膀胱炎": "N30",
            "尿道炎": "N34",
            "前列腺炎": "N41",
            "盆腔炎": "N70-N73",
            "子宫内膜异位症": "N80",
            "多囊卵巢综合征": "E28.2",
            "子宫肌瘤": "D25",
            "甲状腺结节": "E04.1",
            "甲状腺炎": "E06",
            "骨质增生": "M47",
            "椎间盘突出": "M51",
            "椎管狭窄": "M48.0",
            "颈椎病": "M47.8",
            "腰椎病": "M47.8",
            "滑膜炎": "M65",
            "纤维肌痛": "M79.7",
            "慢性疲劳综合征": "G93.3",
        }

    def _load_umls_mapping(self) -> Dict[str, str]:
        """加载UMLS医学概念编码映射表 - 基于统一医学语言系统"""
        return {
            "高血压": "C0020481",
            "糖尿病": "C0011847",
            "肺炎": "C0032285",
            "冠心病": "C0018799",
            "心肌梗死": "C0027051",
            "脑梗死": "C0018681",
            "哮喘": "C0004096",
            "慢性阻塞性肺疾病": "C0010054",
            "肺结核": "C0036341",
            "艾滋病": "C0001967",
            "癌症": "C0006826",
            "胃癌": "C0016644",
            "肺癌": "C0024117",
            "肝癌": "C0022684",
            "乳腺癌": "C0006336",
            "结肠癌": "C0007102",
            "直肠癌": "C0015682",
            "胰腺癌": "C0025202",
            "卵巢癌": "C0028754",
            "前列腺癌": "C0033249",
            "甲状腺癌": "C0039254",
            "白血病": "C0023448",
            "淋巴瘤": "C0024235",
            "胆结石": "C0013268",
            "肾结石": "C0035078",
            "胆囊炎": "C0013269",
            "阑尾炎": "C0023813",
            "胰腺炎": "C0030789",
            "胃炎": "C0017632",
            "消化性溃疡": "C0034063",
            "肝硬化": "C0023415",
            "脂肪肝": "C0035542",
            "慢性肾脏病": "C0023868",
            "急性肾损伤": "C0856079",
            "肾病综合征": "C0027423",
            "肾衰竭": "C0034054",
            "贫血": "C0003238",
            "血小板减少": "C0031233",
            "系统性红斑狼疮": "C0033707",
            "类风湿关节炎": "C0035341",
            "强直性脊柱炎": "C0007634",
            "痛风": "C0017634",
            "骨质疏松": "C0030567",
            "骨折": "C0016261",
            "癫痫": "C0019210",
            "帕金森病": "C0030569",
            "阿尔茨海默病": "C0002395",
            "抑郁症": "C0011570",
            "焦虑症": "C0003638",
            "精神分裂症": "C0036346",
            "失眠": "C0022208",
            "肥胖症": "C0028757",
            "甲状腺功能亢进": "C0040046",
            "甲状腺功能减退": "C0040047",
            "骨关节炎": "C0015540",
            "偏头痛": "C0026762",
            "带状疱疹": "C0004238",
            "流感": "C0019694",
            "普通感冒": "C0008254",
            "手足口病": "C1272219",
            "水痘": "C0016070",
            "麻疹": "C0024671",
            "风疹": "C0035801",
            "流行性腮腺炎": "C0024539",
            "猩红热": "C0036170",
            "百日咳": "C0008262",
            "白喉": "C0010160",
            "破伤风": "C0040542",
            "狂犬病": "C0034048",
            "病毒性肝炎": "C0019684",
            "梅毒": "C0036697",
            "淋病": "C0028552",
            "细菌性痢疾": "C0013239",
            "伤寒": "C0036272",
            "霍乱": "C0008041",
            "疟疾": "C0024432",
            "登革热": "C0011664",
            "心律失常": "C0024109",
            "心房颤动": "C0004232",
            "心力衰竭": "C0018787",
            "心绞痛": "C0018786",
            "心肌炎": "C0024617",
            "心包炎": "C0024616",
            "胸腔积液": "C0034141",
            "气胸": "C0034143",
            "肺栓塞": "C0031341",
            "支气管扩张": "C0004095",
            "肺脓肿": "C0034144",
            "呼吸衰竭": "C0034150",
            "睡眠呼吸暂停": "C0037207",
            "鼻窦炎": "C0036430",
            "扁桃体炎": "C0036435",
            "咽炎": "C0036436",
            "喉炎": "C0012611",
            "中耳炎": "C0028760",
            "青光眼": "C0017657",
            "白内障": "C0006067",
            "牙周病": "C0031202",
            "龋齿": "C0013238",
            "脂溢性皮炎": "C0013241",
            "湿疹": "C0013242",
            "银屑病": "C0035543",
            "荨麻疹": "C0035544",
            "痤疮": "C0001849",
            "脱发": "C0001850",
            "白癜风": "C0042331",
            "过敏性紫癜": "C0018597",
            "深静脉血栓": "C0015230",
            "短暂性脑缺血发作": "C0036292",
            "脑出血": "C0018679",
            "蛛网膜下腔出血": "C0036293",
            "多发性硬化": "C0027759",
            "肌萎缩侧索硬化": "C0018802",
            "重症肌无力": "C0027760",
            "吉兰-巴雷综合征": "C0017646",
            "腕管综合征": "C0030572",
            "三叉神经痛": "C0036301",
            "面神经麻痹": "C0015541",
            "双相情感障碍": "C0007692",
            "创伤后应激障碍": "C0034266",
            "强迫症": "C0028759",
            "注意缺陷多动障碍": "C0014867",
            "自闭症谱系障碍": "C0014868",
            "酒精使用障碍": "C0001305",
            "创伤性脑损伤": "C0036306",
            "脊髓损伤": "C0035930",
            "败血症": "C0013267",
            "尿路感染": "C0035642",
            "脑膜炎": "C0025250",
            "脑炎": "C0013271",
            "骨髓炎": "C0025251",
            "炎性肠病": "C0035645",
            "克罗恩病": "C0018579",
            "溃疡性结肠炎": "C0035646",
            "肠易激综合征": "C0018578",
            "胃食管反流病": "C0018577",
            "膀胱炎": "C0007097",
            "尿道炎": "C0036310",
            "前列腺炎": "C0033250",
            "盆腔炎": "C0030792",
            "子宫内膜异位症": "C0014871",
            "多囊卵巢综合征": "C0035648",
            "子宫肌瘤": "C0035649",
            "乳腺增生": "C0035650",
            "乳腺炎": "C0026331",
            "甲状腺结节": "C0039255",
            "甲状腺炎": "C0039256",
            "痛风性关节炎": "C0017635",
            "骨质增生": "C0036317",
            "椎间盘突出": "C0036318",
            "椎管狭窄": "C0036319",
            "颈椎病": "C0036321",
            "腰椎病": "C0036322",
            "滑膜炎": "C0036323",
            "阿司匹林": "C0005890",
            "布洛芬": "C0013227",
            "青霉素": "C0014819",
            "阿莫西林": "C0004057",
            "头孢氨苄": "C0004063",
            "头孢拉定": "C0004064",
            "头孢呋辛": "C0004065",
            "头孢曲松": "C0004066",
            "红霉素": "C0015231",
            "阿奇霉素": "C0004072",
            "克拉霉素": "C0015232",
            "四环素": "C0038459",
            "左氧氟沙星": "C0015234",
            "环丙沙星": "C0015235",
            "诺氟沙星": "C0015236",
            "甲硝唑": "C0025252",
            "替硝唑": "C0025253",
            "氯霉素": "C0015237",
            "万古霉素": "C0015238",
            "利福平": "C0015239",
            "异烟肼": "C0015240",
            "胰岛素": "C0022847",
            "二甲双胍": "C0025560",
            "硝苯地平": "C0028855",
            "氨氯地平": "C0028856",
            "美托洛尔": "C0025565",
            "卡托普利": "C0007222",
            "依那普利": "C0007223",
            "厄贝沙坦": "C0028861",
            "缬沙坦": "C0028862",
            "氢氯噻嗪": "C0019368",
            "呋塞米": "C0015244",
            "螺内酯": "C0035545",
            "硝酸甘油": "C0028865",
            "肝素": "C0019296",
            "华法林": "C0019369",
            "氯吡格雷": "C0028868",
            "阿托伐他汀": "C0028869",
            "瑞舒伐他汀": "C0028870",
            "沙丁胺醇": "C0035547",
            "布地奈德": "C0009263",
            "奥美拉唑": "C0028877",
            "兰索拉唑": "C0028878",
            "法莫替丁": "C0015245",
            "雷尼替丁": "C0035549",
            "泼尼松": "C0030361",
            "地塞米松": "C0011214",
            "甲状腺素": "C0036329",
            "甲巯咪唑": "C0025574",
        }

    def normalize_name(self, name: str, entity_type: str) -> str:
        """规范化实体名称 - 将同义词/缩写映射到标准名称"""
        name = name.strip()
        
        if name in self.abbreviation_map:
            return self.abbreviation_map[name]
        
        for standard_name, synonyms in self.synonym_rules.get(entity_type, {}).items():
            if name == standard_name or name.lower() == standard_name.lower():
                return standard_name
            if name in synonyms or name.lower() in [s.lower() for s in synonyms]:
                return standard_name
        
        return name

    def compute_similarity(self, name1: str, name2: str) -> float:
        """计算两个名称的相似度"""
        name1 = name1.lower()
        name2 = name2.lower()
        
        if name1 == name2:
            return 1.0
        
        if name1 in name2 or name2 in name1:
            return 0.9
        
        common_chars = sum(1 for c in name1 if c in name2)
        max_len = max(len(name1), len(name2))
        if max_len == 0:
            return 0.0
        
        return common_chars / max_len

    def disambiguate(self, entities: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """消歧实体列表 - 合并指称同一实体的不同表述，支持多类型标签"""
        normalized_map = {}
        
        for entity in entities:
            name = entity.get("name", "")
            entity_type = entity.get("type", "")
            
            normalized_name = self.normalize_name(name, entity_type)
            
            if normalized_name not in normalized_map:
                normalized_map[normalized_name] = {
                    "name": normalized_name,
                    "types": [entity_type] if entity_type else [],
                    "properties": entity.get("properties", {}),
                    "original_names": [],
                    "sources": [],
                }
            
            if entity_type and entity_type not in normalized_map[normalized_name]["types"]:
                normalized_map[normalized_name]["types"].append(entity_type)
            
            if name not in normalized_map[normalized_name]["original_names"]:
                normalized_map[normalized_name]["original_names"].append(name)
            
            source = entity.get("properties", {}).get("source")
            if source and source not in normalized_map[normalized_name]["sources"]:
                normalized_map[normalized_name]["sources"].append(source)
            
            existing_props = normalized_map[normalized_name]["properties"]
            new_props = entity.get("properties", {})
            for key, value in new_props.items():
                if key not in existing_props:
                    existing_props[key] = value
        
        return list(normalized_map.values())


class RelationAligner:
    """关系对齐模块 - 将自然语言关系映射到标准关系类型"""

    def __init__(self):
        self.relation_rules = self._load_relation_rules()
        self.valid_relations = self._load_valid_relations()

    def _load_relation_rules(self) -> Dict[str, List[str]]:
        """加载关系映射规则"""
        return {
            "HAS_SYMPTOM": ["表现为", "症状包括", "症状有", "出现", "伴有", "具有", "症状是", "症状为", "表现", "症状"],
            "CAUSED_BY": ["由...引起", "原因是", "由于", "因为", "因", "病因", "导致", "引起"],
            "DRUG_FOR": ["用于治疗", "适用于", "适应症", "针对", "用于"],
            "TREATED_BY": ["治疗方案", "治疗方法", "治疗", "疗法", "医治", "诊治", "疗法为"],
            "SIDE_EFFECT": ["副作用", "不良反应", "不良反应有", "副作用包括"],
            "INDICATES": ["提示", "表明", "可能提示", "提示可能", "意味着"],
            "BELONGS_TO": ["属于", "归类于", "分类为", "属于科室"],
            "COMPLICATED_BY": ["并发症", "并发", "合并症"],
            "ASSOCIATED_WITH": ["相关", "与...相关", "关联", "有关"],
            "PREVENTS": ["预防", "防止", "避免", "用于预防", "预防性使用"],
            "DIAGNOSED_BY": ["诊断", "检查", "检测", "诊断方法", "确诊", "明确诊断"],
            "SUGGESTS": ["提示可能", "疑似", "考虑", "倾向于", "可能为"],
            "RULES_OUT": ["排除", "排除诊断", "不支持", "不符合"],
            "DIFFERENTIAL_DIAGNOSIS": ["鉴别诊断", "鉴别", "区别", "区分"],
            "DIAGNOSTIC_CRITERIA": ["诊断标准", "符合标准", "满足条件"],
            "PROGNOSIS": ["预后", "预后评估", "预后判断"],
            "RISK_FACTOR": ["危险因素", "风险因素", "高危因素"],
            "WARNING_SIGN": ["警示症状", "危险信号", "红旗征"],
        }

    def _load_valid_relations(self) -> Dict[str, Dict[str, List[str]]]:
        """加载有效的实体类型-关系组合"""
        return {
            "Disease": {
                "HAS_SYMPTOM": ["Symptom"],
                "CAUSED_BY": ["Disease", "Drug", "RiskFactor"],
                "TREATED_BY": ["Treatment", "Drug"],
                "COMPLICATED_BY": ["Disease"],
                "ASSOCIATED_WITH": ["Disease", "Symptom", "Drug", "Examination"],
                "BELONGS_TO": ["Department"],
                "DIAGNOSED_BY": ["Examination"],
                "DIAGNOSTIC_CRITERIA": ["DiagnosticCriteria"],
                "PROGNOSIS": ["Prognosis"],
            },
            "Symptom": {
                "INDICATES": ["Disease"],
                "ASSOCIATED_WITH": ["Disease", "Symptom", "Examination"],
                "SUGGESTS": ["Disease"],
                "WARNING_SIGN": ["Disease"],
            },
            "Drug": {
                "DRUG_FOR": ["Disease", "Symptom"],
                "SIDE_EFFECT": ["Symptom"],
                "ASSOCIATED_WITH": ["Drug", "Disease"],
            },
            "Treatment": {
                "TREATED_BY": ["Disease"],
            },
            "Examination": {
                "DIAGNOSED_BY": ["Disease", "Symptom"],
            },
            "Anatomy": {
                "ASSOCIATED_WITH": ["Disease", "Symptom"],
            },
            "Department": {
                "BELONGS_TO": ["Disease"],
            },
        }

    def align_relation(self, relation_text: str) -> str:
        """将自然语言关系文本映射到标准关系类型 - 优先匹配更长的模式"""
        relation_text = relation_text.strip()
        
        # 收集所有可能的匹配，按模式长度降序排序，优先选择最长匹配
        matches = []
        for standard_relation, patterns in self.relation_rules.items():
            for pattern in patterns:
                if pattern in relation_text or relation_text in pattern:
                    matches.append((len(pattern), standard_relation))
        
        if matches:
            # 按模式长度降序排序，优先返回最长匹配
            matches.sort(key=lambda x: x[0], reverse=True)
            return matches[0][1]
        
        return relation_text

    def validate_relation(self, source_type: str, target_type: str, relation_type: str) -> bool:
        """验证关系是否符合本体约束"""
        source_valid = self.valid_relations.get(source_type, {})
        
        if relation_type not in source_valid:
            return False
        
        valid_targets = source_valid.get(relation_type, [])
        
        if not valid_targets:
            return True
        
        return target_type in valid_targets


class KnowledgeFusionEngine:
    """知识融合引擎 - 整合实体消歧、关系对齐和标准本体链接"""

    def __init__(self):
        self.entity_disambiguator = EntityDisambiguator()
        self.relation_aligner = RelationAligner()

    def fuse(self, entities: List[Dict[str, Any]], relationships: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
        """融合实体和关系 - 支持多类型实体"""
        fused_entities = self.entity_disambiguator.disambiguate(entities)
        
        entity_name_map = {e["name"]: e for e in fused_entities}
        
        fused_relationships = []
        for rel in relationships:
            source_name = self.entity_disambiguator.normalize_name(rel["source"], rel.get("source_type", "Disease"))
            target_name = self.entity_disambiguator.normalize_name(rel["target"], rel.get("target_type", "Symptom"))
            relation_type = self.relation_aligner.align_relation(rel["type"])
            
            if source_name in entity_name_map and target_name in entity_name_map:
                source_types = entity_name_map[source_name].get("types", [])
                target_types = entity_name_map[target_name].get("types", [])
                
                if self._validate_multi_type_relation(source_types, target_types, relation_type):
                    fused_relationships.append({
                        "source": source_name,
                        "target": target_name,
                        "type": relation_type,
                        "properties": rel.get("properties", {}),
                    })
        
        return fused_entities, fused_relationships
    
    def _validate_multi_type_relation(self, source_types: List[str], target_types: List[str], relation_type: str) -> bool:
        """验证多类型实体之间的关系是否符合本体约束"""
        if not source_types or not target_types:
            return False
        
        for source_type in source_types:
            for target_type in target_types:
                if self.relation_aligner.validate_relation(source_type, target_type, relation_type):
                    return True
        
        return False

    def link_to_standard_ontology(self, entities: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """链接实体到标准医学本体 - 支持多类型实体"""
        linked_entities = []
        
        for entity in entities:
            linked = {**entity}
            entity_name = entity.get("name", "")
            entity_types = entity.get("types", [entity.get("type", "")])
            
            if "Disease" in entity_types and entity_name in self.entity_disambiguator.icd10_mapping:
                linked["icd10_code"] = self.entity_disambiguator.icd10_mapping[entity_name]
            
            if entity_name in self.entity_disambiguator.umls_mapping:
                linked["umls_code"] = self.entity_disambiguator.umls_mapping[entity_name]
            
            linked_entities.append(linked)
        
        return linked_entities